edition = "2021"

condense_wildcard_suffixes = true
match_block_trailing_comma = true

reorder_imports = true
imports_granularity = "Crate"

use_field_init_shorthand = true
use_try_shorthand = true

normalize_comments = true

format_macro_bodies = true
