[package]
name = "ark-ed-on-bn254"
version.workspace = true
authors.workspace = true
description = "A Twisted Edwards curve defined over the scalar field of the BN254 curve"
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/ark-ed-on-bn254/"
keywords.workspace = true
categories.workspace = true
include.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
ark-ff = { version = "0.4.0", default-features = false }
ark-ec = { version = "0.4.0", default-features = false }
ark-std = { version = "0.4.0", default-features = false }
ark-r1cs-std = { version = "0.4.0", default-features = false, optional = true }
ark-bn254 = { version = "0.4.0", path = "../bn254", default-features = false, features = [ "scalar_field" ] }

[dev-dependencies]
ark-relations = { version = "0.4.0", default-features = false }
ark-serialize = { version = "0.4.0", default-features = false }
ark-algebra-test-templates = { version = "0.4.0", default-features = false }
ark-curve-constraint-tests = { path = "../curve-constraint-tests", default-features = false }

[features]
default = []
std = [ "ark-std/std", "ark-ff/std", "ark-ec/std", "ark-bn254/std" ]
r1cs = ["ark-r1cs-std"]
