# See https://github.com/DavidAnson/markdownlint#rules--aliases for list of markdown lint codes
default: true
# MD01 lint blocks having header's incrementing by more than # at a time.
MD001: false
MD007: { indent: 4 }
# MD013 blocks long lines
MD013: false
MD024: { siblings_only: true }
MD025: false
# MD033 lint blocks HTML in MD
MD033: false
# MD036 no-emphasis-as-heading
MD036: false
MD041: false
