use crate::*;
use ark_algebra_test_templates::*;

test_group!(te; EdwardsProjective; te);

/// Worked test vectors taken directly from ERC-2494 (EIP-2494), the Baby Jubjub
/// specification: <https://eips.ethereum.org/EIPS/eip-2494>.
///
/// These "literature tests" pin the implementation to the concrete numeric
/// examples given in the standard, complementing the generic, property-based
/// tests generated by `test_group!` above.
mod eip2494 {
    use crate::{EdwardsAffine, EdwardsConfig, Fr};
    use ark_ec::{twisted_edwards::TECurveConfig, AffineRepr};
    use ark_ff::{MontFp, PrimeField};

    /// The neutral element of the group is `O = (0, 1)`.
    fn identity() -> EdwardsAffine {
        EdwardsAffine::new_unchecked(MontFp!("0"), MontFp!("1"))
    }

    /// EIP-2494 "Addition of points" worked example.
    #[test]
    fn test_point_addition() {
        let p1 = EdwardsAffine::new_unchecked(
            MontFp!(
                "17777552123799933955779906779655732241715742912184938656739573121738514868268"
            ),
            MontFp!("2626589144620713026669568689430873010625803728049924121243784502389097019475"),
        );
        let p2 = EdwardsAffine::new_unchecked(
            MontFp!(
                "16540640123574156134436876038791482806971768689494387082833631921987005038935"
            ),
            MontFp!(
                "20819045374670962167435360035096875258406992893633759881276124905556507972311"
            ),
        );
        let expected = EdwardsAffine::new_unchecked(
            MontFp!("7916061937171219682591368294088513039687205273691143098332585753343424131937"),
            MontFp!(
                "14035240266687799601661095864649209771790948434046947201833777492504781204499"
            ),
        );
        assert_eq!(p1 + p2, expected.into_group());
    }

    /// EIP-2494 "Doubling a point" worked example.
    #[test]
    fn test_point_doubling() {
        let p1 = EdwardsAffine::new_unchecked(
            MontFp!(
                "17777552123799933955779906779655732241715742912184938656739573121738514868268"
            ),
            MontFp!("2626589144620713026669568689430873010625803728049924121243784502389097019475"),
        );
        let expected = EdwardsAffine::new_unchecked(
            MontFp!("6890855772600357754907169075114257697580319025794532037257385534741338397365"),
            MontFp!("4338620300185947561074059802482547481416142213883829469920100239455078257889"),
        );
        assert_eq!(p1 + p1, expected.into_group());
    }

    /// EIP-2494 membership examples: `O = (0, 1)` is on the curve, `(1, 0)` is not.
    #[test]
    fn test_on_curve() {
        assert!(identity().is_on_curve());
        let off_curve = EdwardsAffine::new_unchecked(MontFp!("1"), MontFp!("0"));
        assert!(!off_curve.is_on_curve());
    }

    /// EIP-2494 defines the base point `B = 8 * G`, where `G` is the generator of
    /// the full curve group. Arkworks uses this prime-order base point `B` as its
    /// `GENERATOR`, so multiplying `G` by the cofactor 8 must recover it.
    #[test]
    fn test_base_point_is_eight_times_generator() {
        let g = EdwardsAffine::new_unchecked(
            MontFp!("995203441582195749578291179787384436505546430278305826713579947235728471134"),
            MontFp!("5472060717959818805561601436314318772137091100104008585924551046643952123905"),
        );
        assert_eq!(g.mul_bigint([8u64]), EdwardsConfig::GENERATOR.into_group());
    }

    /// EIP-2494: the base point `B` has prime order `l` (the scalar field
    /// modulus), so `l * B` yields the neutral element `O`.
    #[test]
    fn test_base_point_order() {
        let b = EdwardsConfig::GENERATOR;
        assert!(b.is_in_correct_subgroup_assuming_on_curve());
        assert_eq!(b.mul_bigint(Fr::MODULUS), identity().into_group());
    }
}
