
name: Lint
on:
  push:
    branches:
      - master
    paths:
      - "**.md"
  pull_request:
    paths:
      - "**.md"

jobs:
  build:
    name: Markdown linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:latest
        env:
          LINTER_RULES_PATH: .github
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MD: true
          MARKDOWN_CONFIG_FILE: .markdownlint.yml
          VALIDATE_PROTOBUF: false
          VALIDATE_JSCPD: false
          # use Python Pylint as the only linter to avoid conflicts
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false
