
name: Lint
on:
  push:
    branches:
      - master
    paths:
      - "**.md"
  pull_request:
    branches: [master]
    paths:
      - "**.md"

jobs:
  build:
    name: Markdown linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          LINTER_RULES_PATH: .github
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MD: true
          MARKDOWN_CONFIG_FILE: .markdownlint.yml
          VALIDATE_PROTOBUF: false
          VALIDATE_JSCPD: false